# Generated by Django 3.0.2 on 2020-01-28 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_director', models.BooleanField(default=False)),
                ('is_standard', models.BooleanField(default=False)),
                ('is_management', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pv',
            fields=[
                ('IA_System_Code', models.AutoField(primary_key=True, serialize=False)),
                ('IA_code', models.CharField(max_length=150)),
                ('Date_recieved', models.DateField()),
                ('Pv_reference', models.CharField(max_length=120, unique=True)),
                ('Source_of_Funding', models.CharField(choices=[('GOG', 'GOG'), ('Others', 'Others')], max_length=50)),
                ('Cost_center', models.CharField(choices=[('Cost Center 1', 'Cost Center 1'), ('Cost Center 2', 'Cost Center 2'), ('Cost Center 3', 'Cost Center 3'), ('Cost Center 4', 'Cost Center 4'), ('Cost Center 5', 'Cost Center 5')], max_length=50)),
                ('Payee', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Account_code', models.CharField(max_length=350)),
                ('Gross_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Withholding_tax', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Net_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Status', models.CharField(choices=[('Completed', 'Completed'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=60)),
                ('Remarks', models.CharField(blank=True, max_length=500)),
                ('Acc_Impress', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=350)),
                ('Date_returned', models.DateField(blank=True, null=True)),
                ('Type_of_accounts', models.CharField(choices=[('Sub CF', 'Sub CF'), ('Special', 'Special'), ('Directors', 'Directors'), ('Operations', 'Operations'), ('LSGDP', 'LSGDP'), ('DWAP', 'DWAP'), ('Capacity(USD)', 'Capacity(USD)')], max_length=100)),
                ('Type_of_pv', models.CharField(choices=[('General', 'General'), ('Honorarium', 'Honorarium')], max_length=20)),
                ('returned_to_chest', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['IA_System_Code'],
            },
        ),
    ]
