# Generated by Django 3.0.2 on 2020-01-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pv',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
