# Generated by Django 3.0.2 on 2020-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0002_auto_20200128_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pv',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
