# Generated by Django 3.0.2 on 2020-02-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0004_auto_20200206_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv',
            name='returned_to_chest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
